export let soundList = [{
    id: 1,
    soundName: "Continue_Appears",
    soundSetName: "DLC_HEIST_PLANNING_BOARD_SOUNDS"
}, {
    id: 2,
    soundName: "CONTINUE",
    soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
    id: 3,
    soundName: "Apt_Style_Purchase",
    soundSetName: "DLC_APT_Apartment_SoundSet"
}, {
    id: 4,
    soundName: "Menu_Accept",
    soundSetName: "Phone_SoundSet_Default"
}, {
    id: 5,
    soundName: "Event_Message_Purple",
    soundSetName: "GTAO_FM_Events_Soundset"
}, {
    id: 6,
    soundName: "LOCAL_PLYR_CASH_COUNTER_COMPLETE",
    soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
    id: 7,
    soundName: "DELETE",
    soundSetName: "HUD_DEATHMATCH_SOUNDSET"
}, {
    id: 8,
    soundName: "ERROR",
    soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
    id: 9,
    soundName: "Beep_Red",
    soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
    id: 10,
    soundName: "Boss_Message_Orange",
    soundSetName: "GTAO_Boss_Goons_FM_Soundset"
}, {
    id: 11,
    soundName: "Goon_Paid_Small",
    soundSetName: "GTAO_Boss_Goons_FM_Soundset"
}, {
    id: 12,
    soundName: "Hack_Failed",
    soundSetName: "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS"
}, {
    id: 13,
    soundName: "Hack_Success",
    soundSetName: "DLC_HEIST_BIOLAB_PREP_HACKING_SOUNDS"
}, {
    id: 14,
    soundName: "Hang_Up",
    soundSetName: "Phone_SoundSet_Michael"
}, {
    id: 15,
    soundName: "Click",
    soundSetName: "DLC_HEIST_HACKING_SNAKE_SOUNDS"
}, {
    id: 16,
    soundName: "CLICK_BACK",
    soundSetName: "WEB_NAVIGATION_SOUNDS_PHONE"
}, {
    id: 17,
    soundName: "Click_Fail",
    soundSetName: "WEB_NAVIGATION_SOUNDS_PHONE"
}, {
    id: 18,
    soundName: "Click_Special",
    soundSetName: "WEB_NAVIGATION_SOUNDS_PHONE"
}, {
    id: 19,
    soundName: "CONFIRM_BEEP",
    soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
    id: 20,
    soundName: "FestiveGift",
    soundSetName: "Feed_Message_Sounds"
}, {
    id: 30,
    soundName: "CHECKPOINT_NORMAL",
    soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
    id: 31,
    soundName: "CHECKPOINT_PERFECT",
    soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
    id: 32,
    soundName: "CHECKPOINT_UNDER_THE_BRIDGE",
    soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
    id: 40,
    soundName: "FocusIn",
    soundSetName: "HintCamSounds"
}, {
    id: 41,
    soundName: "FocusOut",
    soundSetName: "HintCamSounds"
}, {
    id: 42,
    soundName: "1st_Person_Transition",
    soundSetName: "PLAYER_SWITCH_CUSTOM_SOUNDSET"
}, {
    id: 43,
    soundName: "BOATS_PLANES_HELIS_BOOM",
    soundSetName: "MP_LOBBY_SOUNDS"
}, {
    id: 44,
    soundName: "CHECKPOINT_MISSED",
    soundSetName: "HUD_MINI_GAME_SOUNDSET"
}, {
    id: 45,
    soundName: "CHARACTER_SELECT",
    soundSetName: "HUD_FRONTEND_DEFAULT_SOUNDSET"
}, {
    id: 46,
    soundName: "5_Second_Timer",
    soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
    id: 50,
    soundName: "NAV",
    soundSetName: "HUD_AMMO_SHOP_SOUNDSET"
}, {
    id: 51,
    soundName: "Nav_Arrow_Ahead",
    soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
    id: 52,
    soundName: "Nav_Arrow_Behind",
    soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
    id: 53,
    soundName: "Nav_Arrow_Left",
    soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
    id: 54,
    soundName: "Nav_Arrow_Right",
    soundSetName: "DLC_HEISTS_GENERAL_FRONTEND_SOUNDS"
}, {
    id: 55,
    soundName: "ScreenFlash",
    soundSetName: "MissionFailedSounds"
}, {
    id: 60,
    soundName: "Bed",
    soundSetName: "WastedSounds"
}, {
    id: 61,
    soundName: "Camera_Shoot",
    soundSetName: "Phone_Soundset_Franklin"
}];